server:
  servlet:
    context-path: /app-sigma
spring:
  application:
    name: spring_jpa_specification
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: punna
    password: punna
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   # use validate in prod
      default_batch_fetch_size: 20
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.springframework.security: DEBUG
